import json
import logging
from typing import Any, Dict, List, Optional

from backend.database import SessionLocal
from backend.models import Merchant, MerchantAnalysis, RevenueForecast, AgentExecution
from backend.services.risk_service import risk_service
from backend.services.forecast_service import forecast_service
from backend.services.churn_service import churn_service
from backend.services.simulation_service import simulation_service
from backend.services.copilot_security import MAX_MESSAGE_CHARS

logger = logging.getLogger("razormind.copilot.context")

PLATFORM_ARCHITECTURE_BRIEF = """
### RazorMind AI — Complete System Architecture & Intelligence

RazorMind is an enterprise-grade Merchant Risk, Revenue Forecasting, and Underwriting Intelligence platform built with FastAPI, PostgreSQL, SQLite, and a modern React frontend.

#### 1. Core Architecture & LangGraph Pipeline (`graphs/merchant_graph.py`):
RazorMind orchestrates a multi-agent decision graph executed in sequence:
`Revenue Agent` → `Forecast Agent` → `Risk Agent` → `Churn Agent` → `KPI & Benchmark Agent` → `Root Cause Agent` → `Recommendation Agent` → `Decision Center Agent` → `Action Plan Agent` → `Executive Report Agent`

#### 2. Dedicated Platform Modules & Pages:
- **Overview Tab**: Merchant KPIs, health status, portfolio summary, payment volume (GMV), authorization success rates, and customer retention metrics.
- **Risk & Attribution Tab**: Real-time composite risk scoring (0–100 scale), risk level ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'), factor weights (Failure 35%, Refund 25%, Retention 20%, Health 20%), and root-cause diagnostic evidence.
- **Revenue Lab Tab**: Multi-month revenue forecasting, confidence intervals (lower/upper bounds), seasonal decomposition, and trend slope.
- **Digital Twin Tab**: Interactive what-if simulation engine modeling the impact of success rate lift, refund reduction, churn mitigation, and customer retention deltas.
- **Action Roadmap Tab**: Structured 30-day tactical operational playbook generated by the Action Plan Agent.
- **Executive Brief Tab**: Comprehensive narrative memo with underwriting confidence, SWOT analysis, and capital allocation recommendations.
- **Telemetry & Traces Tab**: Real-time agent execution telemetry, execution status (`SUCCESS`, `FAILED`), latency tracking, and error logs.
- **Advisor AI (This Chat)**: Production ChatGPT-style copilot answering questions about merchants, project architecture, and general domains.

#### 3. Machine Learning Models & Algorithms:
- **Composite Risk Engine (`risk_service.py`)**: Weighted algorithmic scoring incorporating failure velocity, refund spikes, retention degradation, and merchant health.
- **Revenue Forecasting Engine (`forecast_service.py`)**: Time-series projection incorporating merchant transaction history, drift analysis, and category seasonality factors.
- **Churn Prediction Engine (`churn_service.py`)**: Scikit-Learn Random Forest model (`models/churn_model.pkl`) with heuristic fallback analyzing order frequency, refund ratios, and customer decay.
- **Digital Twin Engine (`simulation_service.py`)**: Mathematical simulation simulating GMV lift, net revenue impact, and loss avoidance.
- **LLM Layer (`ollama_streaming_service.py`)**: Local Ollama token streaming with multi-turn conversation memory and robust fallback.
"""

PROJECT_KEYWORDS = (
    "razormind", "project", "architecture", "langgraph", "workflow", "platform",
    "what does this project do", "how does this app work", "how does razormind work",
    "overview tab", "revenue lab", "digital twin", "executive brief", "action roadmap",
    "telemetry", "traces", "agent", "agents", "which models", "pipeline", "backend",
    "frontend", "database", "postgres", "sqlite", "who built", "what is this",
)

MERCHANT_KEYWORDS = (
    "merchant", "kpi", "risk", "churn", "forecast", "revenue", "gmv", "refund",
    "retention", "success rate", "health", "score", "underwriting", "bottleneck",
    "root cause", "playbook", "what is happening", "why is", "why are", "explain this merchant",
    "explain forecast", "explain risk", "explain churn", "simulate", "simulation",
    "recommendation", "m000", "m00",
)

GENERAL_KEYWORDS = (
    "transformer", "attention", "neural network", "deep learning", "python",
    "fastapi", "react", "javascript", "typescript", "upi", "razorpay", "stripe",
    "sql", "docker", "kubernetes", "algorithm", "data structure", "interview",
    "tell me a joke", "write a poem", "translate", "how to", "what is a", "explain",
)


def _clip(text: Optional[str], n: int = 1800) -> str:
    if not text:
        return ""
    s = str(text)
    return s if len(s) <= n else s[:n] + "\n…[truncated]"


def _safe_json(value: Any):
    if not value:
        return None
    if isinstance(value, (dict, list)):
        return value
    try:
        return json.loads(value)
    except Exception:
        return value


class CopilotContextService:
    def classify_intent(self, query: str, mode: str = "general", merchant_id: Optional[str] = None) -> str:
        """
        Intelligently routes the query into:
        - 'MERCHANT': When query asks about a specific merchant, metrics, risk, churn, forecasts, or when in merchant mode and query is context-relevant.
        - 'PROJECT': When query asks about the RazorMind system, architecture, LangGraph, models, tabs, or platform design.
        - 'GENERAL': Standard knowledge / coding / general Q&A (avoids bloating prompt with merchant ledger).
        """
        q = (query or "").lower().strip()
        if not q:
            return "MERCHANT" if (mode == "merchant" and merchant_id) else "GENERAL"

        # Check for explicit merchant reference or merchant ID pattern
        if any(f"m{i:04d}" in q for i in range(1, 100)) or "m000" in q or "this merchant" in q or "selected merchant" in q:
            return "MERCHANT"

        # Check project architecture keywords
        is_project_query = any(k in q for k in PROJECT_KEYWORDS)
        is_merchant_query = any(k in q for k in MERCHANT_KEYWORDS)

        if is_project_query and not is_merchant_query:
            return "PROJECT"

        if mode == "merchant" and merchant_id:
            # If in merchant mode, check if the query is a general knowledge question (e.g. "What is FastAPI?")
            # vs merchant question (e.g. "Why is churn high?")
            if is_merchant_query or "why" in q or "how" in q or "what is happening" in q or "status" in q:
                return "MERCHANT"
            # If query matches general concepts explicitly without merchant terms:
            for gk in GENERAL_KEYWORDS:
                if gk in q and not is_merchant_query:
                    return "GENERAL"
            return "MERCHANT"

        if is_merchant_query and merchant_id:
            return "MERCHANT"

        if is_project_query:
            return "PROJECT"

        return "GENERAL"

    def build_project_context(self, dashboard: Optional[dict] = None) -> Dict[str, Any]:
        """Context builder specifically for RazorMind system, architecture, and platform queries."""
        dashboard = dashboard or {}
        active_tab = dashboard.get("active_tab") or dashboard.get("tab")
        parts = [
            PLATFORM_ARCHITECTURE_BRIEF,
            "### Instructions for Project Queries:",
            "- Explain the RazorMind platform accurately based on the architecture above.",
            "- Mention relevant tabs, agents, models, and workflows.",
            "- Format responses cleanly with clear headings and bullet points."
        ]
        if active_tab:
            parts.append(f"- User is currently inspecting UI tab: `{active_tab}`")

        return {
            "merchant_found": False,
            "formatted_text": "\n\n".join(parts),
            "agents_consulted": ["LangGraph Orchestrator", "RazorMind Architecture Engine"],
            "debug_notes": [f"Current UI tab: {active_tab}"] if active_tab else [],
            "risk_score": None,
            "churn_probability": None,
        }

    def build_general_context(self) -> Dict[str, Any]:
        """Minimal clean context for general knowledge mode (no prompt bloat)."""
        return {
            "merchant_found": False,
            "formatted_text": (
                "You are acting in General AI Mode. Answer the user's question directly, clearly, "
                "and thoroughly like ChatGPT or Claude. Do not bring up unprompted merchant data."
            ),
            "agents_consulted": [],
            "debug_notes": [],
            "risk_score": None,
            "churn_probability": None,
        }

    def build_merchant_context(
        self,
        merchant_id: Optional[str],
        dashboard: Optional[dict] = None,
        debug: bool = False,
    ) -> Dict[str, Any]:
        """Comprehensive merchant context aggregation layer for Advisor AI."""
        result = {
            "merchant_found": False,
            "formatted_text": "",
            "agents_consulted": [],
            "debug_notes": [],
            "risk_score": None,
            "churn_probability": None,
        }
        parts: List[str] = [PLATFORM_ARCHITECTURE_BRIEF]
        agents: List[str] = []
        debug_notes: List[str] = []
        dashboard = dashboard or {}

        tab = dashboard.get("active_tab") or dashboard.get("tab")
        if tab:
            parts.append(f"### Current Dashboard State\n- Active UI Tab: `{tab}`")
            debug_notes.append(f"User is viewing tab `{tab}`.")

        if dashboard.get("ui_errors"):
            parts.append("### Client-Reported UI Diagnostics\n" + "\n".join(f"- {e}" for e in dashboard["ui_errors"]))
            debug_notes.append("Client reported UI errors.")

        db = SessionLocal()
        try:
            if not merchant_id:
                debug_notes.append("No merchant bound to this thread.")
                parts.append("### Merchant Binding\nNo merchant is currently selected. Ask user to pick a merchant or ask general questions.")
            else:
                m = db.query(Merchant).filter(Merchant.merchant_id == merchant_id).first()
                if not m:
                    debug_notes.append(f"Merchant `{merchant_id}` was not found in Postgres.")
                    parts.append(f"### Merchant Binding\nMerchant ID `{merchant_id}` was NOT found in database.")
                else:
                    result["merchant_found"] = True
                    agents.extend(["Revenue Agent", "KPI & Benchmark Agent"])
                    
                    # 1. Live Risk Calculation
                    live_risk = risk_service.calculate_merchant_risk(m)
                    result["risk_score"] = live_risk.get("risk_score")
                    agents.append("Risk Agent")

                    # 2. Live Revenue Forecast
                    live_forecast = forecast_service.generate_forecast(m, months_ahead=3)
                    agents.append("Forecast Agent")

                    # 3. Live Churn Prediction
                    live_churn = churn_service.predict_churn(m)
                    result["churn_probability"] = live_churn.get("churn_probability")
                    agents.append("Churn Agent")

                    # 4. Digital Twin Simulation Baseline
                    try:
                        twin = simulation_service.run_simulation(m, success_rate_delta=0.0, refund_rate_delta=0.0, churn_rate_delta=0.0)
                        agents.append("Digital Twin Agent")
                    except Exception as e:
                        twin = None
                        debug_notes.append(f"Digital Twin baseline: {e}")

                    # Merchant Profile
                    parts.append(
                        "\n".join([
                            f"### Live Merchant Profile — {m.merchant_id} ({m.merchant_name or 'Unknown'})",
                            f"- Category: {m.category or 'E-Commerce'} | Industry: {m.industry or 'Retail'} | Status: {m.merchant_status or 'Active'}",
                            f"- Total Revenue (GMV): INR {float(m.total_revenue or 0):,.2f}",
                            f"- Total Transactions: {int(m.total_transactions or 0):,}",
                            f"- Authorization Success Rate: {float(m.success_rate or 0):.2f}%",
                            f"- Refund Rate: {float(m.refund_rate or 0):.2f}%",
                            f"- Active Customers: {int(m.active_customers or 0):,} | Repeat Customers: {int(m.repeat_customers or 0):,}",
                            f"- Customer Retention Score: {float(m.retention_score or 0):.2f}% | Average Order Value (AOV): INR {float(m.avg_order_value or 0):,.2f}",
                            f"- Merchant Health Score: {float(m.merchant_health_score or 0):.1f}/100",
                        ])
                    )

                    # Risk Attribution
                    risk_factors_str = "; ".join(live_risk.get("risk_factors") or live_risk.get("factors") or ["No critical risk factor"])
                    parts.append(
                        "\n".join([
                            "### Risk Assessment (Risk Agent)",
                            f"- Composite Risk Score: {live_risk.get('risk_score')}/100 — Level: `{live_risk.get('risk_level')}` (Severity: {live_risk.get('severity')})",
                            "- Risk Factor Weights: Payment Failure 35%, Refunds 25%, Retention 20%, Health 20%",
                            f"- Primary Risk Drivers: {risk_factors_str}",
                        ])
                    )

                    # Churn Analysis
                    parts.append(
                        "\n".join([
                            "### Churn Prediction (Churn Agent)",
                            f"- Churn Probability: {live_churn.get('churn_probability')}% — Risk Level: `{live_churn.get('churn_risk_level')}` ({live_churn.get('urgency')})",
                            f"- Key Drivers: {'; '.join(live_churn.get('key_drivers') or ['Stable customer retention'])}",
                            f"- Recommended Playbook: {live_churn.get('recommended_playbook', 'Standard account management')}",
                        ])
                    )

                    # Revenue Forecasts
                    if live_forecast:
                        flines = ["### Revenue Forecast Projections (Forecast Agent)"]
                        for f in live_forecast[:4]:
                            month = f.get("month") or f.get("forecast_month") or "Horizon"
                            pred = f.get("predicted_revenue") or f.get("revenue") or 0
                            lo = f.get("confidence_lower", f.get("lower", 0))
                            hi = f.get("confidence_upper", f.get("upper", 0))
                            flines.append(f"- Month '{month}': Expected INR {float(pred):,.2f} (Confidence Bounds: INR {float(lo or 0):,.2f} – INR {float(hi or 0):,.2f})")
                        parts.append("\n".join(flines))

                    # Persisted Multi-Agent Analysis
                    analysis = (
                        db.query(MerchantAnalysis)
                        .filter(MerchantAnalysis.merchant_id == merchant_id)
                        .order_by(MerchantAnalysis.id.desc())
                        .first()
                    )
                    if analysis:
                        agents.extend(["Decision Center Agent", "Executive Report Agent"])
                        parts.append(
                            "\n".join([
                                "### Multi-Agent Governance & Decision",
                                f"- Underwriting Decision: `{analysis.decision}` | Risk Level: `{analysis.risk_level}` (Score: {analysis.risk_score})",
                                f"- Executive Brief Summary:\n{_clip(analysis.executive_report, 1200)}",
                            ])
                        )
                        rc = _safe_json(analysis.root_causes)
                        if rc:
                            agents.append("Root Cause Agent")
                            if isinstance(rc, dict):
                                parts.append(
                                    "\n".join([
                                        "### Root Cause Bottlenecks (Root Cause Agent)",
                                        f"- Primary Bottleneck: {rc.get('primary_bottleneck', 'None')}",
                                        f"- Severity: {rc.get('severity', 'LOW')}",
                                        f"- Diagnostic Evidence: {_clip(str(rc.get('evidence', rc)), 600)}",
                                    ])
                                )
                            else:
                                parts.append(f"### Root Cause Bottlenecks\n{_clip(str(rc), 600)}")
                        if analysis.action_plan:
                            agents.append("Action Plan Agent")
                            parts.append(f"### 30-Day Tactical Playbook (Action Plan Agent)\n{_clip(analysis.action_plan, 1000)}")
                        recs = _safe_json(analysis.recommendations)
                        if recs:
                            agents.append("Recommendation Agent")
                            if isinstance(recs, list):
                                parts.append("### Recommendations:\n" + "\n".join(f"- {r}" for r in recs[:8]))
                            else:
                                parts.append(f"### Recommendations:\n{_clip(str(recs), 600)}")

                    # Digital Twin Baseline
                    if twin:
                        sim_summary = {k: twin[k] for k in ["baseline_revenue", "simulated_revenue", "revenue_growth_percent", "net_gain"] if k in twin}
                        parts.append(f"### Digital Twin Baseline (Simulation Engine)\n- Metrics: {json.dumps(sim_summary, default=str)}")

                    # Agent Execution Telemetry
                    traces = (
                        db.query(AgentExecution)
                        .filter(AgentExecution.merchant_id == merchant_id)
                        .order_by(AgentExecution.id.desc())
                        .limit(8)
                        .all()
                    )
                    if traces:
                        agents.append("Telemetry Engine")
                        tlines = ["### Recent Agent Telemetry Logs"]
                        for t in traces:
                            tlines.append(f"- {t.agent_name}: `{t.status}` (Latency: {t.execution_time}s) — {_clip(t.output_summary, 120)}")
                        parts.append("\n".join(tlines))

            if debug or debug_notes:
                parts.append("### System Debug & Telemetry Notes\n" + "\n".join(f"- {n}" for n in debug_notes))

        except Exception as e:
            logger.exception("copilot context build failed")
            debug_notes.append(f"Context builder exception: {e}")
            parts.append(f"### Context Fallback Notice\nCould not query all merchant tables ({e}). Answering from available knowledge.")
            try:
                db.rollback()
            except Exception:
                pass
        finally:
            db.close()

        text = "\n\n".join(parts)
        if len(text) > MAX_MESSAGE_CHARS:
            text = text[:MAX_MESSAGE_CHARS] + "\n…[context truncated to fit model window]"

        result["formatted_text"] = text
        result["agents_consulted"] = sorted(set(agents))
        result["debug_notes"] = debug_notes
        return result

    def build(
        self,
        merchant_id: Optional[str],
        query: str = "",
        mode: str = "general",
        dashboard: Optional[dict] = None,
        debug: bool = False,
    ) -> Dict[str, Any]:
        """Intelligent routing dispatcher."""
        intent = self.classify_intent(query, mode=mode, merchant_id=merchant_id)
        if intent == "GENERAL":
            return self.build_general_context()
        elif intent == "PROJECT":
            return self.build_project_context(dashboard=dashboard)
        else:
            return self.build_merchant_context(merchant_id=merchant_id, dashboard=dashboard, debug=debug)


copilot_context_service = CopilotContextService()
